import './global.css';
import type { Metadata } from 'next';
import { Noto_Serif_TC } from 'next/font/google';
import Header from './components/header/Header';

const notoSerif = Noto_Serif_TC({
  variable: '--font-noto-serif',
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  robots: { index: true, follow: true },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css"
        precedence="default"
      />
      <body
        className={`${notoSerif.variable} antialiased duration-300 ease-in-out dark:bg-gray-800 bg-gray-100`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
